# Generated by Django 3.0.5 on 2020-05-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_auto_20200503_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_type_profile_set', to='matrimony.CurrencyType'),
        ),
    ]
